version: 2.1

jobs:
  build: 
    working_directory: ~/obsrv-query-engine
    docker: 
      - image: "circleci/node:14.18.2-bullseye-browsers-legacy"
    steps:
      - checkout
      - run: npm run build
       
  test:
    working_directory: ~/obsrv-query-engine
    docker:
      - image: "circleci/node:14.18.2-bullseye-browsers-legacy"
    steps:
      - checkout
      - run: npm run coverage
      - store_artifacts:
          path: coverage

workflows:
  build_and_test:
    jobs:
      - build
      - test: 
          requires:
            - build